#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# 从 public/assets/hdri/{dosch,hdrimaps} 扫描 .hdr，生成 src/core/isoEnvironments.ts
import os

PUB  = "/Users/huabinxu/WorkBuddy/2026-08-11-21-17-02/MRender-Web/public/assets/hdri"
OUT  = "/Users/huabinxu/WorkBuddy/2026-08-11-21-17-02/MRender-Web/src/core/isoEnvironments.ts"

# (源文件夹, 显示标签, 卡片底色)
sources = [
    ("dosch",    "Dosch",    [0.06, 0.07, 0.10]),
    ("hdrimaps", "HDRIMAPS", [0.10, 0.08, 0.07]),
]

def sanitize_id(s):
    out = []
    for ch in s:
        out.append(ch if (ch.isalnum() or ch in "-_") else "_")
    return "".join(out)

entries = {}
for folder, tag, bg in sources:
    root = os.path.join(PUB, folder)
    if not os.path.isdir(root):
        continue
    for dirpath, _, files in os.walk(root):
        for f in files:
            if not f.lower().endswith(".hdr"):
                continue
            full = os.path.join(dirpath, f)
            rel = os.path.relpath(full, PUB)                 # dosch/HC/DH-301HC.hdr
            url = "/assets/hdri/" + rel.replace(os.sep, "/")  # 服务URL（public 根）
            slug = os.path.splitext(f)[0]                    # 缩略图文件名 = hdr 文件名(去扩展名)
            thumb = "/assets/hdri/thumbs/" + slug + ".png"
            rel_to_src = os.path.relpath(full, root).rsplit(".hdr", 1)[0].split(os.sep)
            sub = rel_to_src[1:] if len(rel_to_src) > 1 else rel_to_src  # 去掉卷名/HDRI 根目录
            rid = "iso_" + folder + "_" + sanitize_id("_".join(sub))
            name = f"{tag} · " + " / ".join(sub)
            entries[rid] = (name, url, bg, thumb)

lines = []
lines.append("// AUTO-GENERATED by scripts/gen_iso_envs.py — 从 Dosch / HDRIMAPS ISO 批量导入的 HDR 环境库")
lines.append("// 源文件在 public/assets/hdri/{dosch,hdrimaps}/。请勿手改，改脚本重跑。")
lines.append("export interface IsoEnv { id: string; name: string; hdrUrl: string; bg: [number, number, number]; thumbUrl: string; }")
lines.append("export const ISO_ENV_PRESETS: IsoEnv[] = [")
for rid, (name, url, bg, thumb) in sorted(entries.items()):
    lines.append(f'  {{ id: "{rid}", name: "{name}", hdrUrl: "{url}", bg: [{bg[0]}, {bg[1]}, {bg[2]}], thumbUrl: "{thumb}" }},')
lines.append("];")
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"generated {len(entries)} entries -> {OUT}")
